# 1. Preprocessing and Feature Engineering

In [19]:
import pandas as pd
import numpy as np

# Only keep data from June 23rd 2025 onwards (date store acquired by new owners)
df = pd.read_csv('../data/aggregated_sales_data.csv')
df['Date'] = pd.to_datetime(df['Date'])
df = df[df['Date'] >= '2025-06-23']

In [20]:
# Determine Baseline Price based on Customer Type, then check discount percentage
conditions = [
    df['Customer Type'] == 'Retail Selling Price',
    df['Customer Type'] == 'Contractor 1',
    df['Customer Type'] == 'Contractor 2',
    df['Customer Type'] == 'Contractor 3'
]

choices = [
    df['Retail Price'],
    df['Contractor 1 Price'],
    df['Contractor 2 Price'],
    df['Contractor 3 Price']
]

baseline = np.select(conditions, choices, default=df['Retail Price'])

# Calculate Discount Percentage
df['Discount_Pct'] = ((baseline - df['Unit Price']) / baseline).round(2)
df.head(10)

,Date,Customer Name,Customer Type,Item No,Product Name,Size,Quantity,Unit Price,Total Sale Price,Standard Cost,Retail Price,Contractor 1 Price,Contractor 2 Price,Contractor 3 Price,Discount_Pct
0,2026-02-19,KL Creation,Contractor 1,3PKMP-13MM,Lint Free Micro Pro - 3 Pk 13mm,Each,1,18.86,18.86,6.60,18.860000,18.860000,18.860000,18.860000,0.0
1,2026-02-19,KL Creation,Contractor 1,5PK TPL GRN,XXL PLASTIC TRAY LINERS,Each,1,7.50,7.50,4.50,7.500000,7.500000,7.500000,7.500000,0.0
2,2026-02-19,KL Creation,Contractor 1,F5241X-001,1G F5241X AURA EG INT,Gallon,1,104.77,104.77,59.10,116.860000,104.770000,96.710000,89.660000,0.0
3,2026-02-19,KL Creation,Contractor 1,F5081X-001,1G F5081X WB CEILING PNT BASE 1,Gallon,1,73.85,73.85,42.58,86.159450,73.846687,68.721756,60.828571,-0.0
4,2026-02-19,"Grieve, Carolyn",Retail Selling Price,K5521X-001,1G K5521X REGAL SLCT MA INT,Gallon,1,96.70,96.70,49.06,96.700000,83.600000,77.560000,68.490000,0.0
5,2026-02-19,Searle Quality Construction,Contractor 1,K2001X-006,COLOUR SAMPLES BASE 1,Half Pint,1,8.04,8.04,2.99,8.040000,8.040000,8.040000,8.040000,0.0
6,2026-02-19,Cash Customer,Retail Selling Price,HB285003,"DYN. 1"" FOAM BRUSH- HIGH DENSITY",Each,2,1.00,2.00,0.30,1.000000,1.000000,1.000000,1.000000,-0.0
7,2026-02-19,Cash Customer,Retail Selling Price,BNC116642,3IN HI DENSITY FM BRUSH WDH,Each,1,1.67,1.67,0.50,1.666667,1.666667,1.666667,1.666667,-0.0
8,2026-02-19,Idrenos,Contractor 2,K6273X-004,QT K6273X BEN SG INT LTX,Quart,1,28.99,28.99,10.44,35.990000,28.990000,28.990000,28.990000,0.0
9,2026-02-19,"Greco, Vanessa",Retail Selling Price,K2001X-006,COLOUR SAMPLES BASE 1,Half Pint,1,8.04,8.04,2.99,8.040000,8.040000,8.040000,8.040000,0.0

In [21]:
# Is_Promo feature
# Logic: If Discount_Pct within Promo discount range and date range, then Is_Promo = 1, else 0
import pandas as pd
import numpy as np

# Ensure Date is datetime
df['Date'] = pd.to_datetime(df['Date'])

# Define Promo Ranges
range_1_start, range_1_end = pd.Timestamp('2025-12-05'), pd.Timestamp('2025-12-31')
range_2_start, range_2_end = pd.Timestamp('2026-02-07'), pd.Timestamp('2026-02-17')

def flag_promo_1(row):
    """Flags the December Promo (Gallons Only)"""
    if row['Customer Name'] != 'Ecommerce, Shopify':
        return 0
    if not (0.14 <= row['Discount_Pct'] <= 0.3):
        return 0
    
    current_date = row['Date']
    # 1st Promo condition: Date range + Gallon size
    if (range_1_start <= current_date <= range_1_end) and (row['Size'] == 'Gallon'):
        return 1
    return 0

def flag_promo_2(row):
    """Flags the February Promo (All Paint/Sizes)"""
    if row['Customer Name'] != 'Ecommerce, Shopify':
        return 0
    if not (0.14 <= row['Discount_Pct'] <= 0.3):
        return 0
    
    current_date = row['Date']
    # 2nd Promo condition: Date range only
    if (range_2_start <= current_date <= range_2_end):
        return 1
    return 0

# Apply the functions to create separate columns
df['Is_Promo_1'] = df.apply(flag_promo_1, axis=1)
df['Is_Promo_2'] = df.apply(flag_promo_2, axis=1)

# Combined Is_Promo for general baseline filtering
df['Is_Promo'] = ((df['Is_Promo_1'] == 1) | (df['Is_Promo_2'] == 1)).astype(int)

df.head(50)

,Date,Customer Name,Customer Type,Item No,Product Name,Size,Quantity,Unit Price,Total Sale Price,Standard Cost,Retail Price,Contractor 1 Price,Contractor 2 Price,Contractor 3 Price,Discount_Pct,Is_Promo_1,Is_Promo_2,Is_Promo
0,2026-02-19,KL Creation,Contractor 1,3PKMP-13MM,Lint Free Micro Pro - 3 Pk 13mm,Each,1,18.86,18.86,6.60,18.860000,18.860000,18.860000,18.860000,0.00,0,0,0
1,2026-02-19,KL Creation,Contractor 1,5PK TPL GRN,XXL PLASTIC TRAY LINERS,Each,1,7.50,7.50,4.50,7.500000,7.500000,7.500000,7.500000,0.00,0,0,0
2,2026-02-19,KL Creation,Contractor 1,F5241X-001,1G F5241X AURA EG INT,Gallon,1,104.77,104.77,59.10,116.860000,104.770000,96.710000,89.660000,0.00,0,0,0
3,2026-02-19,KL Creation,Contractor 1,F5081X-001,1G F5081X WB CEILING PNT BASE 1,Gallon,1,73.85,73.85,42.58,86.159450,73.846687,68.721756,60.828571,-0.00,0,0,0
4,2026-02-19,"Grieve, Carolyn",Retail Selling Price,K5521X-001,1G K5521X REGAL SLCT MA INT,Gallon,1,96.70,96.70,49.06,96.700000,83.600000,77.560000,68.490000,0.00,0,0,0
5,2026-02-19,Searle Quality Construction,Contractor 1,K2001X-006,COLOUR SAMPLES BASE 1,Half Pint,1,8.04,8.04,2.99,8.040000,8.040000,8.040000,8.040000,0.00,0,0,0
6,2026-02-19,Cash Customer,Retail Selling Price,HB285003,"DYN. 1"" FOAM BRUSH- HIGH DENSITY",Each,2,1.00,2.00,0.30,1.000000,1.000000,1.000000,1.000000,-0.00,0,0,0
7,2026-02-19,Cash Customer,Retail Selling Price,BNC116642,3IN HI DENSITY FM BRUSH WDH,Each,1,1.67,1.67,0.50,1.666667,1.666667,1.666667,1.666667,-0.00,0,0,0
8,2026-02-19,Idrenos,Contractor 2,K6273X-004,QT K6273X BEN SG INT LTX,Quart,1,28.99,28.99,10.44,35.990000,28.990000,28.990000,28.990000,0.00,0,0,0
9,2026-02-19,"Greco, Vanessa",Retail Selling Price,K2001X-006,COLOUR SAMPLES BASE 1,Half Pint,1,8.04,8.04,2.99,8.040000,8.040000,8.040000,8.040000,0.00,0,0,0
10,2026-02-19,"Lazar, Jasmine",Contractor 2,F5491X-001,1G F5491X REGAL SLCT EG INT,1 gallon,2,77.56,155.12,49.06,96.700000,83.600000,77.560000,68.490000,0.00,0,0,0
11,2026-02-19,"Lazar, Jasmine",Contractor 2,Q3211-2,"Wooster Shortcut Brush Poly 2""",Each,1,11.51,11.51,6.33,12.660000,12.660000,11.509091,11.509091,-0.00,0,0,0
12,2026-02-19,"Hulleman Painti, Matt",Contractor 1,HP3920.7X.1FR,1G HP3920.7X HP COMMAND WB ST TNTBL WHT,1 gallon,1,108.72,108.72,64.93,118.854109,112.843239,103.854766,99.846225,0.04,0,0,0
13,2026-02-19,"Fagnani, Louie",Contractor 1,K70309-017,50MM BRUSH K70309 PLUS RAT,Each,1,11.99,11.99,3.74,12.990000,11.990000,10.990000,10.490000,0.00,0,0,0
14,2026-02-19,"Fagnani, Louie",Contractor 1,K70310-017,63MM BRUSH K70310 PLUS RAT,Each,1,12.99,12.99,4.62,13.990000,12.990000,11.990000,10.990000,0.00,0,0,0
15,2026-02-19,"Johnny, Mike",Retail Selling Price,K5521X-001,1G K5521X REGAL SLCT MA INT,Gallon,1,96.70,96.70,49.06,96.700000,83.600000,77.560000,68.490000,0.00,0,0,0
16,2026-02-19,Cash Customer,Retail Selling Price,F5491X-004,NEW REGAL EGGSHELL,Quart,1,38.99,38.99,16.60,38.990000,33.990000,33.990000,33.990000,0.00,0,0,0
17,2026-02-19,Cash Customer,Retail Selling Price,"2X3"" M88 HI",2PK M88 MICRO RFL HIGH PILE,Each,1,5.97,5.97,1.79,5.966667,5.114286,5.114286,5.114286,-0.00,0,0,0
18,2026-02-18,"Johnny, Mike",Retail Selling Price,K5521X-001,1G K5521X REGAL SLCT MA INT,Gallon,1,96.70,96.70,49.06,96.700000,83.600000,77.560000,68.490000,0.00,0,0,0
19,2026-02-18,"Whitfield, Drew",Retail Selling Price,K2001X-006,COLOUR SAMPLES BASE 1,Half Pint,1,8.04,8.04,2.99,8.040000,8.040000,8.040000,8.040000,0.00,0,0,0
20,2026-02-18,"Whitfield, Drew",Retail Selling Price,K2001X-006,COLOUR SAMPLES BASE 1,Half Pint,1,8.04,8.04,2.99,8.040000,8.040000,8.040000,8.040000,0.00,0,0,0
21,2026-02-18,"Whitfield, Drew",Retail Selling Price,3 BRASS SET,3 Mini brass wire set,Each,1,8.99,8.99,2.80,8.990000,6.990000,5.990000,4.990000,0.00,0,0,0
22,2026-02-18,"Whitfield, Drew",Retail Selling Price,K2001X-006,COLOUR SAMPLES BASE 1,Half Pint,1,8.04,8.04,2.99,8.040000,8.040000,8.040000,8.040000,0.00,0,0,0
23,2026-02-18,"Brodzik, Paul",Retail Selling Price,F6241X-001,1G F6241X BEN MA INT LTX,Gallon,1,75.14,75.14,38.22,75.140000,67.630000,62.260000,56.890000,0.00,0,0,0
24,2026-02-18,"Brodzik, Paul",Retail Selling Price,3PKLF-13MM,13MM LINT FREE REFILLS,Each,1,15.07,15.07,24.00,53.333333,48.000000,46.153846,43.636364,0.72,0,0,0
25,2026-02-18,That Handy Guy,Contractor 2,K5521X-001,1G K5521X REGAL SLCT MA INT,Gallon,1,77.56,77.56,49.06,96.700000,83.600000,77.560000,68.490000,0.00,0,0,0
26,2026-02-18,That Handy Guy,Contractor 2,K5521X-001,1G K5521X REGAL SLCT MA INT,Gallon,1,77.56,77.56,49.06,96.700000,83.600000,77.560000,68.490000,0.00,0,0,0
27,2026-02-18,Flood Rescue,Contractor 2,HP3920.7X.1FR,1G HP3920.7X HP COMMAND WB ST TNTBL WHT,1 gallon,1,100.06,100.06,64.93,118.854109,112.843239,103.854766,99.846225,0.04,0,0,0
28,2026-02-17,KL Creation,Contractor 1,F5241X-001,1G F5241X AURA EG INT,Gallon,2,104.77,209.54,59.10,116.860000,104.770000,96.710000,89.660000,0.00,0,0,0
29,2026-02-17,KL Creation,Contractor 1,F5243X-001,1G F5243X AURA EG INT,Gallon,1,104.77,104.77,59.10,116.860000,104.770000,96.710000,89.660000,0.00,0,0,0
30,2026-02-17,KL Creation,Contractor 1,F5261X-004,QT F5261X AURA SAT INT,Quart,1,41.46,41.46,21.39,46.650000,41.460000,41.460000,37.320000,0.00,0,0,0
31,2026-02-17,KL Creation,Contractor 1,60401,Dynamic Painter's Plastic 9x400,Each,1,29.84,29.84,16.41,29.836364,29.836364,28.293103,28.293103,-0.00,0,0,0
32,2026-02-17,Prestige Decor & Contractor,Retail Selling Price,217143,"Delicate Frog Tape 1 1/2""",Each,1,17.13,17.13,10.28,17.133333,17.133333,17.133333,15.815385,0.00,0,0,0
33,2026-02-17,Prestige Decor & Contractor,Retail Selling Price,7990-02 BLOCK GREEN,Block 69X98 Siasponge superfine green,Each,2,2.99,5.98,0.74,2.990000,1.990000,1.990000,1.990000,0.00,0,0,0
34,2026-02-17,"Johnny, Mike",Retail Selling Price,F5491X-001,1G F5491X REGAL SLCT EG INT,1 gallon,1,96.70,96.70,49.06,96.700000,83.600000,77.560000,68.490000,0.00,0,0,0
35,2026-02-17,"Johnny, Mike",Retail Selling Price,JE085001,Dynamic Dyna Patch Pro 8 oz.,Each,1,9.64,9.64,4.82,9.640000,8.763636,8.763636,8.763636,0.00,0,0,0
36,2026-02-17,"Johnny, Mike",Retail Selling Price,LF-5MM,5mm lint free,Each,1,7.19,7.19,3.76,13.593637,11.117682,11.117682,11.117682,0.47,0,0,0
37,2026-02-17,"Romaniuk, Elaine",Retail Selling Price,K5521X-004,QT K5521X REGAL SLCT MA INT,Quart,1,35.24,35.24,16.82,35.240000,30.210000,30.210000,30.210000,0.00,0,0,0
38,2026-02-17,Cash Customer,Retail Selling Price,F55101-001,1G F55101 REGAL SLCT SG INT WT,Gallon,1,87.84,87.84,49.06,96.700000,83.600000,77.560000,68.490000,0.09,0,0,0
39,2026-02-17,Cash Customer,Retail Selling Price,K5521X-001,1G K5521X REGAL SLCT MA INT,Gallon,1,87.84,87.84,49.06,96.700000,83.600000,77.560000,68.490000,0.09,0,0,0
40,2026-02-17,Cash Customer,Retail Selling Price,PS 5PC 100BR,"5PC LF PAINT SET, 100MM",Each,1,15.00,15.00,24.00,53.333333,48.000000,46.153846,43.636364,0.72,0,0,0
41,2026-02-17,Cash Customer,Retail Selling Price,71162,DAP DRYDEX SPACKLING INT/EXT 237ML,Each,1,8.64,8.64,3.89,8.644444,7.780000,7.780000,7.780000,0.00,0,0,0
42,2026-02-17,Cash Customer,Retail Selling Price,PK-20,"2"" putty knife",Each,1,1.99,1.99,0.60,1.990000,1.990000,1.990000,1.990000,0.00,0,0,0
43,2026-02-17,Cash Customer,Retail Selling Price,0070.1351.01,7990 Combi Block Super fine Green,Each,1,2.99,2.99,1.00,2.990000,2.990000,1.990000,1.990000,0.00,0,0,0
44,2026-02-17,"Minor, Kelly",Contractor 1,F5491X-004,NEW REGAL EGGSHELL,Quart,1,33.99,33.99,16.60,38.990000,33.990000,33.990000,33.990000,0.00,0,0,0
45,2026-02-17,Sam Stein,Contractor 2,F5371X-001,1G F5371X ULTRA SPEC 500 LS INT,Gallon,6,44.99,269.94,28.59,63.990000,47.990000,44.990000,42.990000,0.00,0,0,0
46,2026-02-17,"Idsinga, Hank",Retail Selling Price,F5081X-001,1G F5081X WB CEILING PNT BASE 1,Gallon,1,86.16,86.16,42.58,86.159450,73.846687,68.721756,60.828571,-0.00,0,0,0
47,2026-02-17,Cash Customer,Retail Selling Price,K04600-004,Fresh Start Stain-block Primer,Quart,1,36.33,36.33,17.26,36.330000,29.520000,29.520000,26.100000,0.00,0,0,0
48,2026-02-17,Cash Customer,Retail Selling Price,F5491X-004,NEW REGAL EGGSHELL,Quart,1,38.99,38.99,16.60,38.990000,33.990000,33.990000,33.990000,0.00,0,0,0
49,2026-02-17,"Peak, Susan",Retail Selling Price,K7921X-001,1G K7921X ADVANCE WB PE,Gallon,1,102.12,102.12,54.04,102.120000,95.730000,89.350000,82.960000,0.00,0,0,0

In [22]:
# Separating Date feature into Day, Month, Year, and Day of the Week

df['Date'] = pd.to_datetime(df['Date'])

idx = df.columns.get_loc('Date') + 1

date_features = [
    ('Year', df['Date'].dt.year),
    ('Month', df['Date'].dt.month),
    ('Day', df['Date'].dt.day),
    ('Day of the Week', df['Date'].dt.day_name())
]

for i, (col_name, data) in enumerate(date_features):
    if col_name in df.columns:
        df.drop(columns=[col_name], inplace=True)
    df.insert(idx + i, col_name, data)

df.head()

,Date,Year,Month,Day,Day of the Week,Customer Name,Customer Type,Item No,Product Name,Size,...,Total Sale Price,Standard Cost,Retail Price,Contractor 1 Price,Contractor 2 Price,Contractor 3 Price,Discount_Pct,Is_Promo_1,Is_Promo_2,Is_Promo
0,2026-02-19,2026,2,19,Thursday,KL Creation,Contractor 1,3PKMP-13MM,Lint Free Micro Pro - 3 Pk 13mm,Each,...,18.86,6.60,18.86000,18.860000,18.860000,18.860000,0.0,0,0,0
1,2026-02-19,2026,2,19,Thursday,KL Creation,Contractor 1,5PK TPL GRN,XXL PLASTIC TRAY LINERS,Each,...,7.50,4.50,7.50000,7.500000,7.500000,7.500000,0.0,0,0,0
2,2026-02-19,2026,2,19,Thursday,KL Creation,Contractor 1,F5241X-001,1G F5241X AURA EG INT,Gallon,...,104.77,59.10,116.86000,104.770000,96.710000,89.660000,0.0,0,0,0
3,2026-02-19,2026,2,19,Thursday,KL Creation,Contractor 1,F5081X-001,1G F5081X WB CEILING PNT BASE 1,Gallon,...,73.85,42.58,86.15945,73.846687,68.721756,60.828571,-0.0,0,0,0
4,2026-02-19,2026,2,19,Thursday,"Grieve, Carolyn",Retail Selling Price,K5521X-001,1G K5521X REGAL SLCT MA INT,Gallon,...,96.70,49.06,96.70000,83.600000,77.560000,68.490000,0.0,0,0,0

In [23]:
# Standardize Size
df['Size'] = df['Size'].replace('1 gallon', 'Gallon')
df['Size'] = df['Size'].replace('18 litre', '5 Gallon')
df['Size'] = df['Size'].replace('4 Lt', 'Gallon')

# Keep only paint items
valid_sizes = ['Gallon', '5 Gallon', 'Quart', 'Half Pint']
df = df[df['Size'].isin(valid_sizes)].copy()
df.head(10)

,Date,Year,Month,Day,Day of the Week,Customer Name,Customer Type,Item No,Product Name,Size,...,Total Sale Price,Standard Cost,Retail Price,Contractor 1 Price,Contractor 2 Price,Contractor 3 Price,Discount_Pct,Is_Promo_1,Is_Promo_2,Is_Promo
2,2026-02-19,2026,2,19,Thursday,KL Creation,Contractor 1,F5241X-001,1G F5241X AURA EG INT,Gallon,...,104.77,59.10,116.860000,104.770000,96.710000,89.660000,0.00,0,0,0
3,2026-02-19,2026,2,19,Thursday,KL Creation,Contractor 1,F5081X-001,1G F5081X WB CEILING PNT BASE 1,Gallon,...,73.85,42.58,86.159450,73.846687,68.721756,60.828571,-0.00,0,0,0
4,2026-02-19,2026,2,19,Thursday,"Grieve, Carolyn",Retail Selling Price,K5521X-001,1G K5521X REGAL SLCT MA INT,Gallon,...,96.70,49.06,96.700000,83.600000,77.560000,68.490000,0.00,0,0,0
5,2026-02-19,2026,2,19,Thursday,Searle Quality Construction,Contractor 1,K2001X-006,COLOUR SAMPLES BASE 1,Half Pint,...,8.04,2.99,8.040000,8.040000,8.040000,8.040000,0.00,0,0,0
8,2026-02-19,2026,2,19,Thursday,Idrenos,Contractor 2,K6273X-004,QT K6273X BEN SG INT LTX,Quart,...,28.99,10.44,35.990000,28.990000,28.990000,28.990000,0.00,0,0,0
9,2026-02-19,2026,2,19,Thursday,"Greco, Vanessa",Retail Selling Price,K2001X-006,COLOUR SAMPLES BASE 1,Half Pint,...,8.04,2.99,8.040000,8.040000,8.040000,8.040000,0.00,0,0,0
10,2026-02-19,2026,2,19,Thursday,"Lazar, Jasmine",Contractor 2,F5491X-001,1G F5491X REGAL SLCT EG INT,Gallon,...,155.12,49.06,96.700000,83.600000,77.560000,68.490000,0.00,0,0,0
12,2026-02-19,2026,2,19,Thursday,"Hulleman Painti, Matt",Contractor 1,HP3920.7X.1FR,1G HP3920.7X HP COMMAND WB ST TNTBL WHT,Gallon,...,108.72,64.93,118.854109,112.843239,103.854766,99.846225,0.04,0,0,0
15,2026-02-19,2026,2,19,Thursday,"Johnny, Mike",Retail Selling Price,K5521X-001,1G K5521X REGAL SLCT MA INT,Gallon,...,96.70,49.06,96.700000,83.600000,77.560000,68.490000,0.00,0,0,0
16,2026-02-19,2026,2,19,Thursday,Cash Customer,Retail Selling Price,F5491X-004,NEW REGAL EGGSHELL,Quart,...,38.99,16.60,38.990000,33.990000,33.990000,33.990000,0.00,0,0,0

In [24]:
# Save the feature-engineered dataset
output_path = "../data/feature_engineered_data.csv"
df.to_csv(output_path, index=False, encoding="utf-8-sig")

output_path

'../data/feature_engineered_data.csv'